services:
  community-postgres:
    container_name: "community-postgres"
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=community
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  default:
    name: infra